# Generated by Django 4.2.4 on 2023-08-13 15:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('currant', '0002_file_columns'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='children',
            field=models.ManyToManyField(blank=True, related_name='parents', to='currant.file'),
        ),
        migrations.AddField(
            model_name='file',
            name='root',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='InputParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('value', models.TextField()),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input_parameters', to='currant.file')),
            ],
        ),
    ]
