# Generated by Django 4.2.4 on 2023-08-14 07:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('currant', '0003_file_children_file_root_inputparameter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('value', models.TextField()),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='OperationSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('value', models.TextField()),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='file',
            name='children',
        ),
        migrations.DeleteModel(
            name='InputParameter',
        ),
        migrations.AddField(
            model_name='operation',
            name='input_files',
            field=models.ManyToManyField(blank=True, related_name='input_parameters', to='currant.file'),
        ),
        migrations.AddField(
            model_name='operation',
            name='output_files',
            field=models.ManyToManyField(blank=True, related_name='output_parameters', to='currant.file'),
        ),
        migrations.AddField(
            model_name='operation',
            name='sequence',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='currant.operationsequence'),
        ),
    ]
