# Generated by Django 4.2.4 on 2023-08-14 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('currant', '0004_operation_operationsequence_remove_file_children_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='sequence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='currant.operationsequence'),
        ),
    ]
