# Generated by Django 4.2.4 on 2023-08-15 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currant', '0005_alter_operation_sequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='file_type',
            field=models.TextField(blank=True, null=True),
        ),
    ]
