# Generated by Django 4.2.4 on 2023-08-18 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currant', '0006_file_file_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='operation_type',
            field=models.CharField(choices=[('APS-DF', 'AlphaPeptStats'), ('PLCHD', 'Placeholder'), ('RQF-PROT', 'QFeatures (Protein) (R)'), ('RQF-PEP', 'QFeatures (Peptide) (R)')], default='PLCHD'),
        ),
    ]
