# Generated by Django 4.2.4 on 2023-08-20 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currant', '0008_operation_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='job_finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='operation',
            name='job_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
