# Generated by Django 4.2.4 on 2023-08-22 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currant', '0010_alter_operation_sequence_coral_file_coral_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='job_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='operation',
            name='job_error_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='operation',
            name='result',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='operation',
            name='operation_type',
            field=models.CharField(choices=[('APS-DF', 'AlphaPeptStats'), ('PLCHD', 'Placeholder'), ('RQF-PROT', 'QFeatures (Protein) (R)'), ('RQF-PEP', 'QFeatures (Peptide) (R)'), ('RQF-NORM', 'QFeatures (Normalization) (R)'), ('RQF-IMP', 'QFeatures (Imputation) (R)')], default='PLCHD'),
        ),
    ]
