# Generated by Django 4.2.4 on 2023-08-24 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currant', '0011_operation_job_error_operation_job_error_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserExtraData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userSource', models.TextField()),
                ('userSourceId', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='operation',
            name='operation_type',
            field=models.CharField(choices=[('APS-DF', 'AlphaPeptStats'), ('PLCHD', 'Placeholder'), ('RQF-PROT', 'QFeatures (Protein) (R)'), ('RQF-PEP', 'QFeatures (Peptide) (R)'), ('RQF-NORM', 'QFeatures (Normalization) (R)'), ('RQF-IMP', 'QFeatures (Imputation) (R)'), ('R-CORR', 'Correlation Matrix (R)')], default='PLCHD'),
        ),
    ]
